package rng.distribution;

import rng.Distribution;
import org.uncommons.maths.random.ExponentialGenerator;
import org.uncommons.maths.random.MersenneTwisterRNG;

/**
 * Class for exponential distribution
 *
 * @author Fran Carpio
 */
public class ExponentialDistribution extends Distribution {

    ExponentialGenerator exponential;
    private final String NAME = "EXP";

    /**
     * Constructor class
     *
     * @param lambda mean value
     * @param seed   initial seed value
     */
    public ExponentialDistribution(double lambda, byte[] seed) {
        super(lambda, seed);
        MersenneTwisterRNG rng = new MersenneTwisterRNG(seed);
        exponential = new ExponentialGenerator(lambda, rng);
    }

    /**
     * Get next value
     *
     * @return double value generated by the RNG
     */
    @Override
    public Double execute() {
        return exponential.nextValue();
    }

    /**
     * Get the distribution name
     *
     * @return string distribution name
     */
    @Override
    public String getDistributionName() {
        return NAME;
    }
}
